Test_1
DrVazelin/altexsoft-lab-2020 pull request #1
Opened 2020-07-29 12:15 UTC by DrVazelin

Fiirst PR, just test

2020-07-29 16:00 UTC, alex-geraschenko requested changes
Забыли добавить .gitignore, поэтому много лишних файлов в коммите

2020-07-29 16:00 UTC, alex-geraschenko commented on Task1_File/Task1_File/App.config
> +        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2" />
Курс по .NET Core

2020-08-04 18:08 UTC, alex-geraschenko requested changes

2020-08-04 18:08 UTC, alex-geraschenko commented on Task1_File/Task1_File/Servises/ShowFile.cs
> +    class ShowFile
Пустой класс. Зачем он здесь?

2020-08-04 18:08 UTC, alex-geraschenko commented on Task1_File/Task1_File/Servises/WordCount.cs
> +    class WordCount
Пустой класс. Зачем он здесь?

2020-08-04 18:08 UTC, alex-geraschenko commented on Task1_File/Task1_File/Servises/WrapLetters.cs
> +    class WrapLetters
Пустой класс. Зачем он здесь?

2020-08-04 18:24 UTC, DrVazelin commented
Добрый вечер, это ещё не финальное решение. Я писал вам в телеграмм, и
предупредил что у меня неделю не будет доступа к машине, вы разрешили
доделать позже. В финальном варианте конечно такого не будет, просто
добавил чтобы не запутаться

вт, 4 авг. 2020 г., 21:08 Alex Geraschenko <notifications@github.com>:

> *@alex-geraschenko* requested changes on this pull request.
> ------------------------------
>
> In Task1_File/Task1_File/Servises/ShowFile.cs
> <https://github.com/DrVazelin/altexsoft-lab-2020/pull/1#discussion_r462412366>
> :
>
> > @@ -0,0 +1,12 @@
>
> +﻿using System;
>
> +using System.Collections.Generic;
>
> +using System.Linq;
>
> +using System.Text;
>
> +using System.Threading.Tasks;
>
> +
>
> +namespace Task1_File.Servises
>
> +{
>
> +    class ShowFile
>
>
> Пустой класс. Зачем он здесь?
> ------------------------------
>
> In Task1_File/Task1_File/Servises/WordCount.cs
> <https://github.com/DrVazelin/altexsoft-lab-2020/pull/1#discussion_r462412475>
> :
>
> > @@ -0,0 +1,12 @@
>
> +﻿using System;
>
> +using System.Collections.Generic;
>
> +using System.Linq;
>
> +using System.Text;
>
> +using System.Threading.Tasks;
>
> +
>
> +namespace Task1_File.Servises
>
> +{
>
> +    class WordCount
>
>
> Пустой класс. Зачем он здесь?
> ------------------------------
>
> In Task1_File/Task1_File/Servises/WrapLetters.cs
> <https://github.com/DrVazelin/altexsoft-lab-2020/pull/1#discussion_r462412534>
> :
>
> > @@ -0,0 +1,12 @@
>
> +﻿using System;
>
> +using System.Collections.Generic;
>
> +using System.Linq;
>
> +using System.Text;
>
> +using System.Threading.Tasks;
>
> +
>
> +namespace Task1_File.Servises
>
> +{
>
> +    class WrapLetters
>
>
> Пустой класс. Зачем он здесь?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/DrVazelin/altexsoft-lab-2020/pull/1#pullrequestreview-457668454>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMVY46NVHSJYXHEL6AGRNMTR7BFCPANCNFSM4PLRCJTQ>
> .
>

2020-08-04 18:29 UTC, alex-geraschenko commented
> Я писал вам в телеграмм, и предупредил что у меня неделю не будет доступа к машине, вы разрешили доделать позже.

А как я могу понять, что это именно Вы писали, если у Вас ник в телеграмм и здесь разные ?

2020-08-04 18:33 UTC, DrVazelin commented
Никак, я поэтому и написал здесь об этом

вт, 4 авг. 2020 г., 21:29 Alex Geraschenko <notifications@github.com>:

> Я писал вам в телеграмм, и предупредил что у меня неделю не будет доступа
> к машине, вы разрешили доделать позже.
>
> А как я могу понять, что это именно Вы писали, если у Вас ники в телеграмм
> и здесь разные ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/DrVazelin/altexsoft-lab-2020/pull/1#issuecomment-668755690>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMVY46LCJRQZGKXGTGOSH2TR7BHRRANCNFSM4PLRCJTQ>
> .
>

2020-08-18 23:28 UTC, merged

2020-08-19 07:56 UTC, alex-geraschenko commented
Если Вы хотите, чтобы Ваш код проверили, то не следует мержить пул реквест до аппрува

2020-08-19 07:58 UTC, DrVazelin commented
Прошу прощения, это вышло нечаянно

ср, 19 авг. 2020 г., 10:56 Alex Geraschenko <notifications@github.com>:

> Если Вы хотите, чтобы Ваш код проверили, то не следует мержить пул реквест
> до аппрува
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/DrVazelin/altexsoft-lab-2020/pull/1#issuecomment-675915778>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMVY46PNJ5I4N5BOTA3POJTSBOASZANCNFSM4PLRCJTQ>
> .
>