Task1
DrVazelin/altexsoft-lab-2020 pull request #4
Opened 2020-08-20 20:51 UTC by DrVazelin

Finished 1st Task

2020-08-26 13:13 UTC, alex-geraschenko requested changes
В пул реквесте не должно быть файлов и папок, которые прописаны в .gitignore

2020-08-27 19:57 UTC, alex-geraschenko requested changes
1. Имена классы должны быть существительными и отображать суть назначения класса
2. Уберите хардкод путей к файлам, иначе программа не будет работать на другом компьютере
3. Добавьте проверку на существование файла перед тем как его читать
4. Уберите дублирование кода для чтения файла
5. Локальные переменные принято называть в `camelCase`

2020-08-27 19:57 UTC, alex-geraschenko commented on Task1_File/Task1_File/Servises/ShowFile.cs
> +                foreach (string dir in dirs)
Нет сортировки

2020-08-27 19:57 UTC, alex-geraschenko commented on Task1_File/Task1_File/Servises/ShowFile.cs
> +                    foreach (string file in files)
Нет сортировки

2020-08-31 12:40 UTC, alex-geraschenko requested changes
Переделайте, наконец, проект на **.NET Core**

2020-08-31 12:40 UTC, alex-geraschenko commented on Task1_File/Task1_File/Assistant/Sort.cs
> +            for(int i = 0; i < mas.Length-1; i++)
Зачем изобретать велосипед? Воспользуйтесь встроенными средствами сортировки

2020-08-31 12:40 UTC, alex-geraschenko commented on Task1_File/Task1_File/Servises/FileCheges.cs
> +        string path = Environment.CurrentDirectory + @"\File.txt";
Имя файла должно задаваться из консоли

2020-08-31 12:40 UTC, alex-geraschenko commented on Task1_File/Task1_File/Servises/FileCheges.cs
> +    public class FileCheges
Не понял, что означает это имя класса

2020-08-31 12:40 UTC, alex-geraschenko commented on Task1_File/Task1_File/Assistant/File.cs
> +        string path = Environment.CurrentDirectory;
Зачем это поле ?

2020-08-31 12:40 UTC, alex-geraschenko commented on Task1_File/Task1_File/Servises/FileCheges.cs
> +            File File = new File();
Локальные переменные принято называть в `camelCase`

2020-08-31 12:40 UTC, alex-geraschenko commented on Task1_File/Task1_File/Servises/Letters.cs
> +        string path= Environment.CurrentDirectory + @"\File.txt";
Имя файла должно задаваться в консоли

2020-08-31 12:40 UTC, alex-geraschenko commented on Task1_File/Task1_File/Servises/Letters.cs
> +            str = File.ReadFromFile(path);
Дублирование кода в разных классах

2020-08-31 12:40 UTC, alex-geraschenko commented on Task1_File/Task1_File/Servises/Word.cs
> +        string path = Environment.CurrentDirectory + @"\File.txt";
Имя файла должно задаваться в консоли

2020-08-31 12:40 UTC, alex-geraschenko commented on Task1_File/Task1_File/Servises/Word.cs
> +            str = File.ReadFromFile(path);
Дублирование кода в разных классах

2020-08-31 20:06 UTC, DrVazelin commented on Task1_File/Task1_File/Assistant/File.cs
> +        string path = Environment.CurrentDirectory;
Это путь, для сохранения файла с изменениями

2020-09-01 08:08 UTC, alex-geraschenko commented on Task1_File/Task1_File/Assistant/File.cs
> +        string path = Environment.CurrentDirectory;
Так перенесите его тогда в метод сохранения

2020-09-01 11:07 UTC, DrVazelin commented on Task1_File/Task1_File/Servises/Letters.cs
> +            str = File.ReadFromFile(path);
Можно вопрос ? А как от этого избавиться, ведь по факту, это просто вызов метода ?

2020-09-01 11:14 UTC, alex-geraschenko commented on Task1_File/Task1_File/Servises/Letters.cs
> +            str = File.ReadFromFile(path);
Сделать базовый класс, а в нем делать проверку на существование файла и его вычитку

2020-09-01 11:26 UTC, DrVazelin commented on Task1_File/Task1_File/Servises/Letters.cs
> +            str = File.ReadFromFile(path);
Ну тогда получиться, что классы Word, Letters и FileChanger имеют общий родительский класс, как по мне, это не верно с точки зрения ООП(простите, может и глупый вопрос, но всё же) ?
Можно в классе File запилить класс CheckUserFile в котором буду проверять на существование и вычитывать сам файл ?

2020-09-01 11:49 UTC, alex-geraschenko commented on Task1_File/Task1_File/Servises/Letters.cs
> +            str = File.ReadFromFile(path);
> Ну тогда получиться, что классы Word, Letters и FileChanger имеют общий родительский класс, как по мне, это не верно с точки зрения ООП(простите, может и глупый вопрос, но всё же) ?

В этом и идея, что будет один базовый класс для работы с файлом. Тут больше зависит, как назвать классы.
Если Вам не нравится наследование, то примените композицию.

2020-09-01 16:33 UTC, alex-geraschenko approved these changes
Хорошо, можно мержить

2020-09-01 16:36 UTC, DrVazelin commented
Спасибо

вт, 1 сент. 2020 г., 19:33 Alex Geraschenko <notifications@github.com>:

> *@alex-geraschenko* approved this pull request.
>
> Хорошо, можно мержить
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/DrVazelin/altexsoft-lab-2020/pull/4#pullrequestreview-479925770>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMVY46LVNCLKJ3U3MNPMVQDSDUO7BANCNFSM4QGSX7SA>
> .
>

2020-09-01 16:45 UTC, alex-geraschenko commented
Для мержа надо нажать кнопку "Merge pull request"

2020-09-01 16:52 UTC, DrVazelin commented
Спасибо, я просто сейчас не дома, отвечаю с телефона, как только буду за
компом, сразу сделаю. Кстати, должен признаться, ваще решение с общем
родителем было более правильным

вт, 1 сент. 2020 г., 19:45 Alex Geraschenko <notifications@github.com>:

> Для мержа надо нажать кнопку "Merge pull request"
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/DrVazelin/altexsoft-lab-2020/pull/4#issuecomment-684991325>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMVY46KNPACF6SLQQ42YVYTSDUQLDANCNFSM4QGSX7SA>
> .
>

2020-09-01 19:55 UTC, merged