Tasks/task2
DrVazelin/altexsoft-lab-2020 pull request #5
Opened 2020-08-21 16:13 UTC by DrVazelin

Added task 2(not finished)

2020-08-21 16:15 UTC, serhii-shkodenko commented
Поменяйте файл .gitignore на например вот этот https://github.com/github/gitignore/blob/master/VisualStudio.gitignore

2020-08-21 17:23 UTC, VladyslavBublii commented
Сделал, спасибо

пт, 21 авг. 2020 г., 19:15 Sergiy <notifications@github.com>:

> Поменяйте файл .gitignore на например вот этот
> https://github.com/github/gitignore/blob/master/VisualStudio.gitignore
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/DrVazelin/altexsoft-lab-2020/pull/5#issuecomment-678373588>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMVY46OQ56RYSXWKHSBDPELSB2MTZANCNFSM4QHOBKEA>
> .
>

2020-08-26 09:20 UTC, alex-geraschenko requested changes
1. Задание должно быть на **.NET Core**
2. В пул реквесте не должно быть файлов и папок, которые прописаны в `.gitignore`
3. Задание не рассматривается пока не будет сдано первое задание

2020-08-26 09:24 UTC, DrVazelin commented
Первое задание сделано, в соседней ветке.
Это задание на коре.
Вот со вторым - вроде, проблема )

ср, 26 авг. 2020 г., 12:20 Alex Geraschenko <notifications@github.com>:

> *@alex-geraschenko* requested changes on this pull request.
>
>    1. Задание должно быть на *.NET Core*
>    2. В пул реквесте не должно быть файлов и папок, которые прописаны в
>    .gitignore
>    3. Задание не рассматривается пока не будет сдано первое задание
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/DrVazelin/altexsoft-lab-2020/pull/5#pullrequestreview-475308272>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMVY46NFWP7HDQEHHCD76EDSCTHV7ANCNFSM4QHOBKEA>
> .
>

2020-08-26 09:27 UTC, DrVazelin commented
Можно вас попросить чекнуть первый таск ?

ср, 26 авг. 2020 г., 12:24 Vlad Bubliu <vladbubliu@gmail.com>:

> Первое задание сделано, в соседней ветке.
> Это задание на коре.
> Вот со вторым - вроде, проблема )
>
> ср, 26 авг. 2020 г., 12:20 Alex Geraschenko <notifications@github.com>:
>
>> *@alex-geraschenko* requested changes on this pull request.
>>
>>    1. Задание должно быть на *.NET Core*
>>    2. В пул реквесте не должно быть файлов и папок, которые прописаны в
>>    .gitignore
>>    3. Задание не рассматривается пока не будет сдано первое задание
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/DrVazelin/altexsoft-lab-2020/pull/5#pullrequestreview-475308272>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AMVY46NFWP7HDQEHHCD76EDSCTHV7ANCNFSM4QHOBKEA>
>> .
>>
>

2020-09-02 20:53 UTC, alex-geraschenko requested changes
1. Вы когда переделаете на **.NET Core**?
2. Создавать отдельный класс под каждую категорию блюд не самая хорошая идея. Лучше читать их из файла
3. Для работы с данными реализуйте шаблоны `Repository` и `UnitOfWork`

2020-09-02 21:02 UTC, DrVazelin commented
> 1. Вы когда переделаете на **.NET Core**?

2020-09-02 21:03 UTC, DrVazelin commented
> 1. Вы когда переделаете на **.NET Core**?

Блин, мой косяк, только сейчас полез в конфиг и увидел ...

2020-09-02 21:04 UTC, DrVazelin commented
> 3\. Для работы с данными реализуйте шаблоны `Repository` и `UnitOfWork`

Я правильно понимаю, что с их помощью получиться реализовать сквозной список ингредиентов ?

2020-09-02 21:50 UTC, alex-geraschenko commented
> > 3\. Для работы с данными реализуйте шаблоны `Repository` и `UnitOfWork`
> 
> Я правильно понимаю, что с их помощью получиться реализовать сквозной список ингредиентов ?

Должно помочь

2020-09-02 21:55 UTC, DrVazelin commented
> 2\. Создавать отдельный класс под каждую категорию блюд не самая хорошая идея. Лучше читать их из файла

И последний вопрос) Сделать так чтобы имя файла == имя класса ?  и класс создавался при чтении этого файла ?

2020-09-03 08:00 UTC, alex-geraschenko commented
> > 2. Создавать отдельный класс под каждую категорию блюд не самая хорошая идея. Лучше читать их из файла
> 
> И последний вопрос) Сделать так чтобы имя файла == имя класса ? и класс создавался при чтении этого файла ?

Да, можно сделать чтобы имя файла == имя класса. Но в этих файлах будет не один класс, и при чтении из файла и десериализации получится список

2020-09-07 18:13 UTC, alex-geraschenko requested changes
Ни один из комментариев из последнего код ревью не исправлен

2020-09-17 12:48 UTC, alex-geraschenko requested changes
1. Пожалуйста, переделайте это задание с учетом 3-го и 4-го, т.к. сейчас структура хранения данных абсолютно не соответствует условию задачи
2. У Вас приктически везде нарушен принцип **Single Responsibility**. Необходимо разделять логику чтения/сохранения данных, ввод данных и их отображение
3. Вы до сих пор не переделали проект под **.NET Core**. Я дальше не вижу смысла проверять Ваши изменения, т.к. сомневаюсь, что Вы такими темпами успеете выполнить все задания к концу модуля.

2020-09-17 12:54 UTC, DrVazelin commented
"Я дальше не вижу смысла проверять Ваши изменения, т.к. сомневаюсь, что Вы
такими темпами успеете выполнить все задания к концу модуля." -Можно, я
хотя бы постараюсь успеть, только в понедельник закрыл хвост в универе,
сейчас времени будет сильно больше

чт, 17 сент. 2020 г., 15:48 Alex Geraschenko <notifications@github.com>:

> *@alex-geraschenko* requested changes on this pull request.
>
>    1. Пожалуйста, переделайте это задание с учетом 3-го и 4-го, т.к.
>    сейчас структура хранения данных абсолютно не соответствует условию задачи
>    2. У Вас приктически везде нарушен принцип *Single Responsibility*.
>    Необходимо разделять логику чтения/сохранения данных, ввод данных и их
>    отображение
>    3. Вы до сих пор не переделали проект под *.NET Core*. Я дальше не
>    вижу смысла проверять Ваши изменения, т.к. сомневаюсь, что Вы такими
>    темпами успеете выполнить все задания к концу модуля.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/DrVazelin/altexsoft-lab-2020/pull/5#pullrequestreview-490555249>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMVY46LMBXJVW5E3ZGJYR7TSGIARXANCNFSM4QHOBKEA>
> .
>

2020-09-29 14:22 UTC, alex-geraschenko commented
Когда будете готовы, отправьте пул реквест на ревью

2020-10-06 16:49 UTC, alex-geraschenko commented
Вы невнимательно читаете комментарии. В одном из них я Вам говорил, что создавать для каждой категории плохо. У вас должно быть по итогу 4 файла: 
1. `categores.json` - список всех категорий и подкатегорий
2. `ingredients.json` - список всех ингредиентов
3. `recipies.json` - список всех рецептов
4. `recipeIngredients.json` - связь много-ко-многим между ингредиентами и рецептами

И соответсвующией репозитории к ним

2020-10-06 16:57 UTC, DrVazelin commented
Спасибо

вт, 6 окт. 2020 г., 19:50 Alex Geraschenko <notifications@github.com>:

> Вы невнимательно читаете комментарии. В одном из них я Вам говорил, что
> создавать для каждой категории плохо. У вас должно быть по итогу 4 файла:
>
>    1. categores.json - список всех категорий и подкатегорий
>    2. ingredients.json - список всех ингредиентов
>    3. recipies.json - список всех рецептов
>    4. recipeIngredients.json - связь много-ко-многим между ингредиентами
>    и рецептами
>
> И соответсвующией репозитории к ним
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/DrVazelin/altexsoft-lab-2020/pull/5#issuecomment-704409550>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMVY46NFXIVAJLQS4LIWN2DSJNDEFANCNFSM4QHOBKEA>
> .
>

2020-10-08 13:09 UTC, merged